name: formatting-check

on: [push]

jobs:
  formatting-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: jpetrucciani/black-check@master
      with:
        path: '.'
