name: poetry-install

on: [push]

jobs:
  poetry-install:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: abatilo/actions-poetry@v1.5.0
      with:
        python_version: 3.8
        poetry_version: 1.0
        args: install
